# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data 101
description: Data Engineering
author: UC Berkeley
baseurl: # the subpath of your site, e.g. /blog
url: https://data101.org # the base hostname & protocol for your site, e.g. http://example.com

# This should be one of eecs, dsus, stat
# (Future) This will control some footer text, and later custom styling.
course_department: dsus
# This should be the page of all class archives
# Typically just / for DS courses (with a visible index page), or /archives if you're hosting your own, or a link to the inst.eecs page
# If you have no archive page, comment this line out or leave blank.
class_archive_path: /
# TODO(setup): update these as needed.
# course_faq: /faq/

# TODO(setup): Set these auxiliary links as you wish - they show up on the top right
aux_links:
  Course Notes: https://data101.org/notes
  DataHub: https://data101.datahub.berkeley.edu

# TODO(template): These need to be documented
# TODO(semester): You may want to review these...
berkeley_theme_options:
  show_logo_in_sidebar: true

# Theme settings
color_scheme: light
search_enabled: true
permalink: pretty
footer: >-
  Powered by <a href="https://github.com/kevinlin1/just-the-class">Just the Class</a>

# Collections for website data
collections:
# Default layouts for each collection type


######################################################################
# Just the Docs / Berkeley Class Site Common Config
# Options below here will likely not need to be configured..
######################################################################
# TODO(template): We should clean these up + standardize...
# TODO(setup): You may want to add additional
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# TODO(template): CSS compilations. Handle warnings...
sass:
  style: expanded
  sass_dir: _sass
  sourcemap: always
  quiet_deps: true
  verbose: false

# Theme settings
theme: just-the-docs
search_enabled: true
heading_anchors: true
permalink: pretty

## Footer Content.
# You should probably not change these, but may add to footer_content if necessary.
# Replace `true` with any additional HTML that you would like to add.
# Footer *must* included the accessibility text defined in footer_custom.html
footer_content: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true
last_edit_time_format: '%m %d, %Y at %H:%M'

# Compilation settings used by compress-html plugin:
# https://github.com/penibelst/jekyll-compress-html/tree/v3.2.0?tab=readme-ov-file
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Native Jeykll build options
# You likely shouldn't need to touch these, but they are documented here just in case.
# https://jekyllrb.com/docs/configuration/options/

# This makes it easier when pushing to a static directory.
# The default false removes files in that directory, which is useful for when you unpublish pages.
# keep_files: false

# Likely not necessary, but a google default for Berkeley
timezone: America/Los_Angeles

# Note: dotfiles are excluded by default. .htaccess is included as a common case.
include:
  - LICENSE
  - .htaccess
  - robots.txt

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - script/
  - spec/
  - node_modules/
